### ISSUE TITLE
Inverse Power

### ISSUE THREAD

**Issue by Monkeigh** [TheTofuShop/Vehicles#43] opened 2020-02-19 16:00 UTC
🚗 **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)

N/A

🔧 **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)

The reworked inverse power from the update of 2/18 (12:34 AM PST), feels a bit sluggish and more over a bit like traction control. The previous inverse power felt like the cars could actually be driven by sliding around and not constantly be planted on the ground. It also made it so that the back end would kick out a bit more on cars such as the FD, MR2, AE86, S2000, and some others. It makes the driving experience a bit better when sliding is involved but I truly liked the old inverse power better.

**Comment by TheAussie** [comment] 2020-02-19 20:16
>  **What is the spawn model or name of the vehicle?** (e.g. zn6 or Toyota 86)
> 
> N/A
> 
>  **What exactly needs to be changed?** (use https://gtamods.com/wiki/Handling.meta for reference)
> 
> The reworked inverse power from the update of 2/18 (12:34 AM PST), feels a bit sluggish and more over a bit like traction control. The previous inverse power felt like the cars could actually be driven by sliding around and not constantly be planted on the ground. It also made it so that the back end would kick out a bit more on cars such as the FD, MR2, AE86, S2000, and some others. It makes the driving experience a bit better when sliding is involved but I truly liked the old inverse power better.

Of course you like the old one better.

**Comment by justalemon** [comment] 2020-02-19 21:19
This repo is for the Vehicles themselves, not the Menu and 3rd party scripts.

**Comment by justalemon** [comment] 2020-02-19 21:33
Ignore that.

**Comment by TheAussie** [comment] 2020-02-21 10:19
Duplicate of #44

**Closed** 2020-02-21 10:19 UTC
Labels: handling
